### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by fahri314** [thiagoralves/EtherSploit-IP#1]
gcc *.c -o ethersploit -lcrypt

```ethersploit.c: In function ‘process_enip_messages’:
ethersploit.c:85:24: warning: format not a string literal and no format arguments [-Wformat-security]
         cli_print(cli, messagebuffer);
                        ^~~~~~~~~~~~~
ethersploit.c: In function ‘send_raw_pccc’:
ethersploit.c:364:24: warning: format not a string literal and no format arguments [-Wformat-security]
         cli_print(cli, messagebuffer);
                        ^~~~~~~~~~~~~
ethersploit.c: In function ‘get_device_info’:
ethersploit.c:607:24: warning: format not a string literal and no format arguments [-Wformat-security]
         cli_print(cli, messagebuffer);
                        ^~~~~~~~~~~~~
/tmp/cc029Nwy.o: In function `establish_enip_connection':
ethersploit.c:(.text+0x65e): undefined reference to `pthread_create'
ethersploit.c:(.text+0x67c): undefined reference to `pthread_detach'
ethersploit.c:(.text+0x857): undefined reference to `pthread_create'
ethersploit.c:(.text+0x875): undefined reference to `pthread_detach'
/tmp/cc029Nwy.o: In function `reboot_plc':
ethersploit.c:(.text+0x1e67): undefined reference to `pthread_cancel'
/tmp/cc029Nwy.o: In function `kill_plc':
ethersploit.c:(.text+0x26d4): undefined reference to `pthread_cancel'
/tmp/cc029Nwy.o: In function `change_ip':
ethersploit.c:(.text+0x2f74): undefined reference to `pthread_cancel'
/tmp/ccVXF9M4.o: In function `cli_start':
hack.c:(.text+0x3ed): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status```

**Comment by thiagoralves** [comment]
Where are you compiling it on? It seems that your system requires explicit
pthread library linking: gcc *.c -o ethersploit -lcrypt -pthread

**Comment by fahri314** [comment]
I tried to stop, reboot, and read the password, but the commands don't work in plc and the processor is used. Only plc information can be read.

Used PLC: micro 850

Stop Example:
![stop](https://user-images.githubusercontent.com/10153883/70217381-1d9ff200-1752-11ea-9b03-4540e0ff5bf1.PNG)

**Comment by thiagoralves** [comment]
Which PLC? This tool is specific for Allen-Bradley PLCs only, more specifically, Micrologix 1400 series (some commands work with Micrologix 1100 as well and might work on the 1200 series too).

**Comment by EmreEkin** [comment]
Allen Bradley PLC MicroLogix 850 Series

**Comment by thiagoralves** [comment]
There is no such thing as MicroLogix 850 series. What you probably have is a micro850, which is not part of the micrologix series. Check https://ab.rockwellautomation.com/Programmable-Controllers/Micro800 and https://ab.rockwellautomation.com/Programmable-Controllers/MicroLogix-Systems

I don't have a micro800 series system to test, but I'm pretty sure it uses a completely different protocol since it is part of a different line of products.
