### ISSUE TITLE
Not able to run the commands

### ISSUE THREAD

**Issue by Pranavthakkar** [thiagoralves/EtherSploit-IP#3]
Hi I've got the same error as the previous user got & as you have suggested `gcc *.c -o ethersploit -lcrypt -pthread` I tried that but, after that, I can't able to do anything getting only this output.

![image](https://user-images.githubusercontent.com/45504952/191745202-e633c8d7-221a-4b43-b58f-d2df19806d88.png)

**what can I do to proceed further??**

**Comment by thiagoralves** [comment]
There is notting wrong on this cropped screenshot of the compilation process
